region = "us-east-1"
environment = "dev"
short_name = "qms"
project = "QMS AI"
owner = "Vatsal Shah"
vpc_id = ""
subnet1 = ""
subnet2 = ""
subnet3 = ""
subnet4 = ""
subnet5 = ""
security_group_id = ""
s3_buckets_list = []
static_website = ""
lambda_execution_role_arn = "arn:aws:iam::120569648189:role/qms-dev-lambda-role"
ecs_task_role_arn = "arn:aws:iam::120569648189:role/qms-dev-ecs-role"
step_function_role_arn = "arn:aws:iam::120569648189:role/qms-dev-step-function-role"
event_bridge_role_arn = "arn:aws:iam::120569648189:role/qms-dev-events-role"
step_function_configs = []
dynamodb_configs = []
lambda_configs = []
