AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda with HTTP API gateway

Parameters:
  Environment:
    Description: Environment for the bucket
    Type: String
    AllowedValues:
      - 'dev'
      - 'qa'
      - 'prod'

Resources:
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub 'complaints-api-${Environment}'
      RouteSelectionExpression: "$request.method $request.path"
      CorsConfiguration:
        MaxAge: 0
        AllowOrigins:
        - "*"
        AllowCredentials: false
        ExposeHeaders:
        - "*"
        AllowMethods:
        - "POST"
        AllowHeaders:
        - "*"
      ProtocolType: HTTP

  IntegrationCategoryinvoke:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      Description: Lambda proxy integration
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:complaints-queue-narrative-${Environment}'
          - /invocations

  IntegrationFetchresults:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      Description: Lambda proxy integration
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:complaints-fetch-results-${Environment}'
          - /invocations

  IntegrationInvokeapi:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      Description: Lambda proxy integration
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:complaints-upload-narrative-${Environment}'
          - /invocations

  IntegrationUiresults:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      Description: Lambda proxy integration
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:complaints-upload-final-results-${Environment}'
          - /invocations

  IntegrationPreloadNarrative:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      Description: Lambda proxy integration
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:complaints-preload-narrative-${Environment}'
          - /invocations

  IntegrationUpdatefinalresults:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      Description: Lambda proxy integration
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:complaints-upload-final-results-${Environment}'
          - /invocations

  ApiRouteCategoryinvoke:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /categoryinvoke"
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref IntegrationCategoryinvoke

  ApiRouteFetchresults:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /fetchresults"
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref IntegrationFetchresults 

  ApiRouteInvokeapi:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /invokeapi"
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref IntegrationInvokeapi

  ApiRouteUiresults:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /uiresults"
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref IntegrationUiresults

  ApiRouteUpdatefinalresults:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /updatefinalresults"
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref IntegrationUpdatefinalresults

  ApiRoutePreloadNarrative:
    Type: AWS::ApiGatewayV2::Route
    DependsOn: IntegrationPreloadNarrative
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "GET /getinitialdata"
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref IntegrationPreloadNarrative

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: !Ref Environment
      Description: Live Stage
      AutoDeploy: true
Outputs:
  APIGatewayId:
    Value: !GetAtt HttpApi.ApiId