AWSTemplateFormatVersion: '2010-09-09'
Description: "Complaints ui cloudfront distro"

Parameters:
  Environment:
    Description: Environment
    Type: String
    AllowedValues:
      - 'dev'
      - 'qa'
      - 'prod'
  DomainName:
    Description: Domain Name for cloudfront distribution
    Type: String
Resources:
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig:
        Description: Complaints UI Origin Access Control
        Name: !Ref AWS::StackName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  CloudfrontDistro:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
          - "GET"
          - "HEAD"
          - "OPTIONS"
          DefaultTTL: 3600
          ForwardedValues:
            QueryString: "true"
            Cookies:
              Forward: "none"
          TargetOriginId: "S3Origin"
          ViewerProtocolPolicy: "redirect-to-https"
        DefaultRootObject: "index.html"
        Enabled: "true"
        HttpVersion: http2
        Origins:
        - Id: "S3Origin"
          DomainName: !Sub ${DomainName}-${Environment}.s3.us-east-1.amazonaws.com
          S3OriginConfig:
            OriginAccessIdentity: ''
          OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
      Tags:
      - Value: '5H5UVU9Z8L'
        Key: 'map-generated'
Outputs:
  CloudfrontDistributionDomainName:
    Value: !GetAtt CloudfrontDistro.DomainName
  CloudfrontDistributionId:
    Value: !GetAtt CloudfrontDistro.Id
  
