AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB Tables for Complaints

Parameters:
  Environment:
    Description: Environment
    Type: String
    AllowedValues:
      - 'dev'
      - 'qa'
      - 'prod'

Resources:

  MqQmsRecordMetadata:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub mq-qms-record-metadata-${Environment}
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "uuid"
      BillingMode: "PROVISIONED"
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "uuid"

  MqQmsComplaintsAuditLog:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub mq-qms-complaints-audit-log-${Environment}
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "PK"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "PK"
      TableClass: "STANDARD"

  MqQmsComplaintsFinalResults:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub mq-qms-complaints-final-results-${Environment}
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "PK"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "PK"
      TableClass: "STANDARD"

  MqQmsInferenceResults:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub mq-qms-inference-results-${Environment}
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "uuid"
      BillingMode: "PROVISIONED"
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "uuid"

  MqQmsLookupMapping:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub mq-qms-lookup-mapping-${Environment}
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "crl_mapping"
      BillingMode: "PROVISIONED"
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "crl_mapping"

  MqQmsModelRouter:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub mq-qms-model-router-${Environment}
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "drugname"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "drugname"
      TableClass: "STANDARD"

  MqQmsPriorityResults:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub mq-qms-priority-results-${Environment}
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "uuid"
      BillingMode: "PROVISIONED"
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "uuid"

  MqQmsUIResults:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub mq-qms-ui-results-${Environment}
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "uuid"
      BillingMode: "PROVISIONED"
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "uuid"

  MqQmsComplaintsUnifiedLookups:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub mq-qms-complaints-unified-lookups-${Environment}
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "PK"
      - AttributeType: "S"
        AttributeName: "SK"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
        - KeyType: "HASH"
          AttributeName: "PK"
        - KeyType: "RANGE"
          AttributeName: "SK"
      TableClass: "STANDARD"

  MqQmsComplaintsErrorcheckAuditLog:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub complaints-errorness-check-audit-log-${Environment}
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "PK"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "PK"
      TableClass: "STANDARD"
