AWSTemplateFormatVersion: '2010-09-09'
Description: "Complaints ui kms key for cloudfront"
Parameters:
  Environment:
    Description: Environment
    Type: String
    AllowedValues:
      - 'dev'
      - 'qa'
      - 'prod'
  DistributionId:
    Description: Cloudfront distribution Id to generate key policy
    Type: String
Resources:
  KMSKeyCloudfront:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action:
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
              Service: cloudfront.amazonaws.com
            Resource: "*"
            Sid: PolicyForCloudFrontPrivateContent        
