
Parameters:
  SQSQueueArn:
    Description: SQS Queue Arn.
    Type: String

  apiGatewayId:
    Description: HTTP apiGateway Id
    Type: String

  SQSQueueName:
    Description: SQS Queue name.
    Type: String

  ErrornessSQSQueueName:
    Description: Errorness SQS Queue Name
    Type: String
  
  ErrornessSQSQueueArn:
    Description: Errorness SQS Queue ARN
    Type: String

  Environment:
    Description: Environment for the bucket
    Type: String
    AllowedValues:
      - 'dev'
      - 'qa'
      - 'prod'

Resources:

  LambdaFunctionComplaintsBulkInsertDynamoDBData:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-bulk-insert-dynamodb-data'
      Timeout: 120
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)
  
  LambdaFunctionComplaintsLevel:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-level-${Environment}'
      Timeout: 120
      Environment:
        Variables:
          audit_table_name: !Sub mq-qms-complaints-audit-log-${Environment}
          metadata_table_name: !Sub mq-qms-record-metadata-${Environment}
          aws_region_name: us-east-1
          lookup_table_name: !Sub mq-qms-complaints-unified-lookups-${Environment}
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaFunctionComplaintsSubcategory:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-subcategory-${Environment}'
      Timeout: 120
      Environment:
        Variables:
          audit_table_name: !Sub mq-qms-complaints-audit-log-${Environment}
          metadata_table_name: !Sub mq-qms-record-metadata-${Environment}
          aws_region_name: us-east-1
          lookup_table_name: !Sub mq-qms-complaints-unified-lookups-${Environment}
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaFunctionComplaintsCrlMapping:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-crl-mapping-${Environment}'
      Timeout: 120
      Environment:
        Variables:
          inference_results_table_name: !Sub mq-qms-inference-results-${Environment}
          audit_table_name: !Sub mq-qms-complaints-audit-log-${Environment}
          aws_region_name: us-east-1
          lookup_table_name: !Sub mq-qms-complaints-unified-lookups-${Environment}
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaFunctionComplaintsPriority:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-priority-${Environment}'
      Timeout: 120
      Environment:
        Variables:
          audit_table_name: !Sub mq-qms-complaints-audit-log-${Environment}
          aws_region_name: us-east-1
          llm_model_id: "anthropic.claude-3-sonnet-20240229-v1:0"
          priority_enabled_flag: 0
          priority_results_table_name: !Sub mq-qms-priority-results-${Environment}
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaFunctionErrornessCheck:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-errorness-check-${Environment}'
      Timeout: 120
      MemorySize: 10240
      EphemeralStorage:
        Size: 1024
      Environment:
        Variables:
          aws_region_name: us-east-1
          secrets_name: !Sub ${Environment}/complaints_errorness_check_secrets
          audit_table_name: !Sub complaints-errorness-check-audit-log-${Environment}
      Layers:
        - !Sub arn:aws:lambda:us-east-1:${AWS::AccountId}:layer:requests:2
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaEventSourceMappingErrornessCheck:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      MaximumBatchingWindowInSeconds: 0
      ScalingConfig:
        MaximumConcurrency: 10
      Enabled: true
      Queues:
        - !Ref ErrornessSQSQueueName
      EventSourceArn: !Ref ErrornessSQSQueueArn
      FunctionName: !GetAtt LambdaFunctionErrornessCheck.Arn

  LambdaFunctionInference:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-mq-qms-inference-${Environment}'
      Timeout: 15
      Environment:
        Variables:
          audit_table_name: !Sub mq-qms-complaints-audit-log-${Environment}
          s3_bucket: !Sub mq-qms-complaints-${Environment}
          state_machine_name: !Sub arn:aws:states:us-east-1:${AWS::AccountId}:stateMachine:complaints-${Environment}
          metadata_table_name: !Sub mq-qms-record-metadata-${Environment}
          aws_region_name: us-east-1
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaEventSourceMappingInference:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      MaximumBatchingWindowInSeconds: 0
      ScalingConfig:
        MaximumConcurrency: 10
      Enabled: true
      Queues:
        - !Ref SQSQueueName
      EventSourceArn: !Ref SQSQueueArn
      FunctionName: !GetAtt LambdaFunctionInference.Arn

  LambdaFunctionPreloadNarrative:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-preload-narrative-${Environment}'
      Timeout: 120
      Environment:
        Variables:
          audit_table_name: !Sub mq-qms-complaints-audit-log-${Environment}
          aws_region_name: us-east-1
          secrets_name: !Sub ${Environment}/complaints_ai_toolkit
      VpcConfig:
        SecurityGroupIds:
          - "sg-0ab1ad2ab29bf5b47"
          - "sg-0f323f85284dc5692"
        SubnetIds:
          - "subnet-0f38324d8a53f81df"
        Ipv6AllowedForDualStack: false
      Layers:
        - !Sub arn:aws:lambda:us-east-1:${AWS::AccountId}:layer:requests:2
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaPermissionPreloadNarrative:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionPreloadNarrative
      Action: "lambda:InvokeFunction"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*/*/getinitialdata
        - ApiId: !Ref apiGatewayId

  LambdaFunctionQueueNarrative:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-queue-narrative-${Environment}'
      Timeout: 120
      Environment:
        Variables:
          audit_table_name: !Sub mq-qms-complaints-audit-log-${Environment}
          complaints_queue_url: !Sub https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/complaints-mq-qms-${Environment}
          aws_region_name: us-east-1
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaPermissionQueueNarrative:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionQueueNarrative
      Action: "lambda:InvokeFunction"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*/*/categoryinvoke
        - ApiId: !Ref apiGatewayId

  LambdaFunctionFetchResult:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-fetch-results-${Environment}'
      Timeout: 120
      Environment:
        Variables:
          audit_table_name: !Sub mq-qms-complaints-audit-log-${Environment}
          final_results_table_name: !Sub mq-qms-complaints-final-results-${Environment}
          aws_region_name: us-east-1
          inference_results_table_name: !Sub mq-qms-inference-results-${Environment}
          lookup_table_name: !Sub mq-qms-complaints-unified-lookups-${Environment}
          priority_results_table_name: !Sub mq-qms-priority-results-${Environment}
      Layers:
        - !Sub arn:aws:lambda:us-east-1:${AWS::AccountId}:layer:requests:2
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaPermissionFetchResult:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionFetchResult
      Action: "lambda:InvokeFunction"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*/*/fetchresults
        - ApiId: !Ref apiGatewayId

  LambdaFunctionUploadNarrative:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-upload-narrative-${Environment}'
      Timeout: 120
      Environment:
        Variables:
          audit_table_name: !Sub mq-qms-complaints-audit-log-${Environment}
          aws_region_name: "us-east-1"
          metadata_table_name: !Sub mq-qms-record-metadata-${Environment}
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaPermissionUploadNarrative:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionUploadNarrative
      Action: "lambda:InvokeFunction"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*/*/invokeapi
        - ApiId: !Ref apiGatewayId

  LambdaFunctionUploadFinalResults:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaFunctionRole.Arn
      FunctionName: !Sub 'complaints-upload-final-results-${Environment}'
      Timeout: 120
      Environment:
        Variables:
          audit_table_name: !Sub mq-qms-complaints-audit-log-${Environment}
          final_results_table_name: !Sub mq-qms-complaints-final-results-${Environment}
          ui_results_table_name: !Sub mq-qms-ui-results-${Environment}
          aws_region_name: us-east-1
          secrets_name: !Sub ${Environment}/complaints_ai_toolkit
          lookup_table_name: !Sub mq-qms-complaints-unified-lookups-${Environment}
      VpcConfig:
        SecurityGroupIds:
          - "sg-0ab1ad2ab29bf5b47"
          - "sg-0f323f85284dc5692"
        SubnetIds:
          - "subnet-0f38324d8a53f81df"
        Ipv6AllowedForDualStack: false
      Layers:
        - !Sub arn:aws:lambda:us-east-1:${AWS::AccountId}:layer:requests:2
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            logger.info("The input event is %s", event)

  LambdaPermissionUploadFinalResults:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionUploadFinalResults
      Action: "lambda:InvokeFunction"
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*/*/uiresults
        - ApiId: !Ref apiGatewayId

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: LambdaFunctionRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - bedrock:*
            - s3:*
            - sagemaker:*
            - ec2:DescribeNetworkInterfaces
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeInstances
            - ec2:AttachNetworkInterface
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:CreateTable
            - dynamodb:GetItem
            - dynamodb:DescribeTable
            - sqs:DeleteMessage
            - sqs:ReceiveMessage
            - sqs:SendMessage
            - sqs:GetQueueAttributes
            - states:ListExecutions
            - states:StartSyncExecution
            - states:StartExecution
            Resource: "*"
          - Effect: Allow
            Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            Resource: !Ref SQSQueueArn
          - Effect: Allow
            Action:
            - secretsmanager:GetResourcePolicy
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            - secretsmanager:ListSecretVersionIds
            Resource: arn:aws:secretsmanager:us-east-1:...:secret:dev/complaints_errorness_check_secrets
          - Effect: Allow
            Action:
            - secretsmanager:GetResourcePolicy
            - secretsmanager:GetSecretValue
            - secretsmanager:DescribeSecret
            - secretsmanager:ListSecretVersionIds
            Resource: arn:aws:secretsmanager:us-east-1:...:secret:dev/complaints_ai_toolkit
