AWSTemplateFormatVersion: '2010-09-09'
Description: Complaints Nested stack
Parameters:
  LambdaRole:
    Description: IAM Role for LambdaRole
    Type: String
  StepFunctionRole:
    Description: IAM Role for StepFunctionRole
    Type: String
  SagemakerRole:
    Description: IAM Role for SagemakerRole
    Type: String
  Environment:
    Description: Environment
    Type: String
    AllowedValues:
      - 'dev'
Resources:

  CloudfrontStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    Properties:
      TemplateURL: https://pwc-complaints-cloudformation-template-files-dev.s3.us-east-1.amazonaws.com/cloudfront-stack.yaml
      TimeoutInMinutes: 5
      Parameters:
        Environment: !Sub '${Environment}'
        DomainName: 'pwc-qms-complaints-ui'

  SQSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://pwc-complaints-cloudformation-template-files-dev.s3.us-east-1.amazonaws.com/sqs-stack.yaml
      TimeoutInMinutes: 5
      Parameters:
        Environment: !Sub '${Environment}'
  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://pwc-complaints-cloudformation-template-files-dev.s3.us-east-1.amazonaws.com/dynamodb-stack.yaml
      TimeoutInMinutes: 5
      Parameters:
        Environment: !Sub '${Environment}'
  APIGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://pwc-complaints-cloudformation-template-files-dev.s3.us-east-1.amazonaws.com/apigateway-stack.yaml
      TimeoutInMinutes: 10
      Parameters:
        Environment: !Sub '${Environment}'

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://pwc-complaints-cloudformation-template-files-dev.s3.us-east-1.amazonaws.com/lambda-stack.yaml
      TimeoutInMinutes: 5
      Parameters:
        LambdaRole: !Sub '${LambdaRole}'
        Environment: !Sub '${Environment}'
        apiGatewayId: !GetAtt 'APIGatewayStack.Outputs.APIGatewayId'
        SQSQueueName: !GetAtt 'SQSStack.Outputs.SQSQueueName'
        SQSQueueArn: !GetAtt 'SQSStack.Outputs.SQSQueueArn'
        ErrornessSQSQueueName: !GetAtt 'SQSStack.Outputs.SQSQueueErrornessInputName'
        ErrornessSQSQueueArn: !GetAtt 'SQSStack.Outputs.SQSQueueErrornessInputArn'
  StateMachineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://pwc-complaints-cloudformation-template-files-dev.s3.us-east-1.amazonaws.com/statemachine-stack.yaml
      TimeoutInMinutes: 5
      Parameters:
        StepFunctionRole: !Sub '${StepFunctionRole}'
        Environment: !Sub '${Environment}'

#  SageMakerStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: https://pwc-complaints-cloudformation-template-files-dev.s3.us-east-1.amazonaws.com/sagemaker-stack.yaml
#      TimeoutInMinutes: 30
#      Parameters:
#        SagemakerRole: !Sub '${SagemakerRole}'
#        ModelsBucket: dev-qms-product-complaints-ai-model-bucket
#        MounjaroCategoryPath: Mounjaro/mounjaro-12-category-model-v1.tar
#        MounjaroCategoryVersion: 1
#        MounjaroLevelPath: Mounjaro/mounjaro-level-model-v4.tar
#        MounjaroLevelVersion: 4
#        TrulicityCategoryPath: Trulicity/trulicity-12-category-model-v1.tar
#        TrulicityCategoryVersion: 1
#       TrulicityLevelPath: Trulicity/tr-level-model-v1.tar
#       TrulicityLevelVersion: 1
