[tox]
envlist = lint, test

[testenv:lint]
usedevelop = true
skip_install = true
description = Run linting tools: flake8, ruff, black
deps =
    isort
    flake8
    ruff
    black
commands =
    isort {toxinidir}/src {toxinidir}/tests --check-only --diff
    flake8 {toxinidir}/src {toxinidir}/tests
    ruff check {toxinidir}/src {toxinidir}/tests
    black {toxinidir}/src {toxinidir}/tests --check --diff

[flake8]
max-line-length = 120
use-flake8-tabs = true
exclude = .git,__pycache__,venv,env,site-packages,.tox

[isort]
profile = black

[ruff]
line-length = 120
select = E,F,W,C,D,S
ignore = E501
exclude = .git,__pycache__,venv,env,site-packages,.tox

[black]
line-length = 120

[testenv:test]
usedevelop = true
skip_install = true
description = Run pytest
deps =
    boto3
    requests
    pytest
    pytest-cov
commands =
    pytest --cov=src --cov-report=term-missing
setenv =
    aws_region_name = us-east-2
    secrets_name = my-secrets