export const complaintsData = [
  {
    Criticality: "NA",
    "Report Type": "NA",
    Category: "NA",
    "Receipt Date": "Aug 04 2025",
    "Case Type": ["Product Complaint"],
    "Due Date": "Oct 02 2025",
  },
  {
    Criticality: "NA",
    "Report Type": "NA",
    Category: "NA",
    "Receipt Date": "Aug 04 2025",
    "Case Type": ["Adverse Event"],
    "Due Date": "Oct 09 2025",
  },
  {
    Criticality: "NA",
    "Report Type": "NA",
    Category: "NA",
    "Receipt Date": "Aug 04 2025",
    "Case Type": ["Product Complaint", "Adverse Event"],
    "Due Date": "Oct 10 2025",
  },
  {
    Criticality: "NA",
    "Report Type": "NA",
    Category: "NA",
    "Receipt Date": "Aug 04 2025",
    "Case Type": ["Product Complaint"],
    "Due Date": "Oct 11 2025",
  },
  {
    Criticality: "NA",
    "Report Type": "NA",
    Category: "NA",
    "Receipt Date": "Aug 04 2025",
    "Case Type": ["Adverse Event"],
    "Due Date": "Oct 12 2025",
  },
  {
    Criticality: "NA",
    "Report Type": "NA",
    Category: "NA",
    "Receipt Date": "Aug 04 2025",
    "Case Type": ["Product Complaint", "Adverse Event"],
    "Due Date": "Oct 13 2025",
  },
  {
    Criticality: "NA",
    "Report Type": "NA",
    Category: "NA",
    "Receipt Date": "Aug 04 2025",
    "Case Type": ["Product Complaint"],
    "Due Date": "Oct 14 2025",
  },
  {
    Criticality: "NA",
    "Report Type": "NA",
    Category: "NA",
    "Receipt Date": "Aug 04 2025",
    "Case Type": ["Adverse Event"],
    "Due Date": "Oct 15 2025",
  },
  {
    Criticality: "NA",
    "Report Type": "NA",
    Category: "NA",
    "Receipt Date": "Aug 04 2025",
    "Case Type": ["Product Complaint", "Adverse Event"],
    "Due Date": "Oct 16 2025",
  },
  {
    Criticality: "NA",
    "Report Type": "NA",
    Category: "NA",
    "Receipt Date": "Aug 04 2025",
    "Case Type": ["Product Complaint"],
    "Due Date": "Oct 17 2025",
  },
];