name: Deploy UI

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 1

    permissions:
      actions: write
      contents: read
      pull-requests: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Event Data
        run: |
          echo "Event type: ${{ github.event_name }}"
          if [[ ${{ github.event_name }} == "pull_request" ]]
          then
            echo "Source Branch: ${{ github.head_ref }}"
            echo "Target Branch: ${{ github.base_ref }}"
          else
            echo "Triggered by branch/tag: ${{ github.ref }}"
          fi
          echo "Commit Sha: ${{ github.sha }}"
          echo "Event Actor: ${{ github.actor }}"

  buildDeploy:
    environment: pwc
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./complaints-qms-ui
    timeout-minutes: 5
    needs: [ setup ]

    permissions:
      actions: write
      contents: read
      pull-requests: read
      security-events: write
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          node -v
          npm ci
          npm install @microsoft/eslint-formatter-sarif --save-dev

      - name: NPM Build Project
        run: export REACT_APP_API_BASE_URL=https://v6o5y5nu0g.execute-api.us-east-1.amazonaws.com/dev/; npm run build --if-present

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::120569648189:role/qms-app-github-role
          role-session-name: rolesession
          aws-region: us-east-1
      - run: aws s3 sync --delete ./build/ s3://pwc-qms-complaints-ui-dev/

