name: QMS Infrastructure Deploy

on:
  push:
    branches: [ terraform ]
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy QMS Infra & App
    runs-on: ubuntu-latest

    env:
      TF_INPUT: "false"
      TF_IN_AUTOMATION: "true"
      AWS_REGION: "us-east-1"
      TFVARS_PATH: conf/dev/terraform.tfvars

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS creds (access keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }} # optional (only if your keys are temporary)
          aws-region: "us-east-1"

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Install Pre-requisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip jq

      - name: Compile Backend
        run: |
          set -euo pipefail
          SRC="src/app"
          if [ -d "$SRC" ]; then
            for d in "$SRC"/*/; do
              [ -d "$d" ] || continue
              base="$(basename "$d")"
              zipPath="$SRC/${base}.zip"
              rm -f "$zipPath"
              (cd "$d" && zip -qr "$PWD/../${base}.zip" .)
            done
          fi

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Plan Terraform Changes
        run: terraform plan -input=false -var-file="conf/dev/terraform.tfvars" -out=tfplan

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan
